name: Restart Odoo on Server

on:
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin main

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart Odoo via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ssh -i chatbot_key.pem azureuser@4.145.88.243<< 'EOF'
            sudo systemctl restart uvicorn
            sudo systemctl status uvicorn
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
