name: SSH into Azure Server

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  ssh-into-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create PEM file from secret
        run: |
          echo "${{ secrets.AZURE_PEM_FILE }}" > development.pem
          chmod 600 development.pem  # Set permissions

      - name: SSH into Azure Server
        run: |
          ssh -i development.pem azureuser@172.188.42.27 "echo 'Successfully connected to Azure!'"
