name: List Files on Server

on:
  push:
    branches:
      - main

jobs:
  list_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

      - name: List files on remote server
        run: |
          ssh -i private_key azureuser@172.188.42.27 "ls -la"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
