name: Merge Repositories

on:
  push:
    branches:
      - main  # Adjust as necessary

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout second-repo
        uses: actions/checkout@v2

      - name: Clone first-repo
        run: |
          git clone https://github.com/2002lokesh/first-repo.git temp-first-repo
          cp -r temp-first-repo/* .  # Copy files from first-repo to second-repo

      - name: Set up Git
        run: |
          git config --global user.email "lokeshkcse314@gmail.com"
          git config --global user.name "2002lokesh"

      - name: Commit changes
        run: |
          git add .  # Stage all changes
          git commit -m "Merge files from first-repo" || echo "No changes to commit"

      - name: Push changes to second-repo
        env:
          GITHUB_TOKEN: ${{ secrets.FIRST_REPO_TOKEN }}  # Use your PAT stored as a secret
        run: |
          git push https://${{ secrets.FIRST_REPO_TOKEN }}@github.com/2002lokesh/second-repo.git main  # Push changes
