name: Merge First Repo Files

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout second-repo
        uses: actions/checkout@v2

      - name: Clone first-repo
        run: |
          git clone https://${{ secrets.FIRST_REPO_TOKEN }}@github.com/2002lokesh/first-repo.git temp-first-repo

      - name: Set Git User
        run: |
          git config --local user.email "lokeshkcse314@gmail.com"  # Set your email
          git config --local user.name "2002lokesh"                # Set your username

      - name: Copy files from first-repo to second-repo
        run: |
          cp -r temp-first-repo/* .  # Copy files to the current directory
          rm -rf temp-first-repo  # Clean up the temp directory

      - name: Commit and push changes
        run: |
          git add .  # Stage all changes
          git commit -m "Merge files from first-repo" || echo "No changes to commit"
          git push origin main  # Push changes to the second-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN
