name: List Server Files

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  list-server-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout First Repository (first-repo)
      - name: Checkout First Repository
        uses: actions/checkout@v2
        with:
          repository: 2002lokesh/first-repo  # Your first repository
          token: ${{ secrets.FIRST_REPO_TOKEN }}  # Your Personal Access Token (PAT)
          path: first-repo  # Path to clone the first repository

      # Step 2: List Files on the Server
      - name: List Files on Server
        uses: appleboy/ssh-action@master
        with:
          host: 172.188.42.27
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your SSH private key from GitHub Secrets
          script: |
            echo "Listing all files in the current directory:"
            ls -la  # List all files
